services:
  db:
    image: postgres:17-alpine
    restart: always
    env_file:
      - path: .env.development
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: